# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    docker-compose.yml                                 :+:    :+:             #
#                                                      +:+                     #
#    By: cbijman <cbijman@student.codam.nl>           +#+                      #
#                                                    +#+                       #
#    Created: 2023/11/13 16:11:44 by cbijman       #+#    #+#                  #
#    Updated: 2024/09/02 18:01:36 by cbijman       ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

services:
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    healthcheck:
      test: mysqladmin ping -h $$DB_HOST --user=$$DB_USER --pass=$$DB_PASS
      interval: 2s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/cbijman/data/database'

  wordpress:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/cbijman/data/wordpress'
  
networks:
 inception:
  driver: bridge
