# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    docker-compose.yml                                 :+:    :+:             #
#                                                      +:+                     #
#    By: cbijman <cbijman@student.codam.nl>           +#+                      #
#                                                    +#+                       #
#    Created: 2023/11/13 16:11:44 by cbijman       #+#    #+#                  #
#    Updated: 2024/09/02 18:01:36 by cbijman       ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

services:
  database:
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h database --user=$$DB_USER --password=$$DB_PASS
      interval: 2s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    networks:
      - network

  nginx:
    build: ./requirements/nginx
    image: nginx
    volumes:
      - wordpress:/var/www/html
    ports:
      - 80:80
    depends_on:
      - wordpress
    networks:
      - network

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/data/database
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/data/wordpress
      o: bind
  
networks:
 network:
  driver: bridge
