# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    docker-compose.yml                                 :+:    :+:             #
#                                                      +:+                     #
#    By: cbijman <cbijman@student.codam.nl>           +#+                      #
#                                                    +#+                       #
#    Created: 2023/11/13 16:11:44 by cbijman       #+#    #+#                  #
#    Updated: 2024/09/02 18:01:36 by cbijman       ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

services:
  database:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception

  wordpress:
    depends_on:
      - database
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    ports:
      - 80:80
    depends_on:
      - wordpress
      - database
    networks:
      - inception

volumes:
  database:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/cbijman/data/database'
  wordpress:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/cbijman/data/wordpress'
  
networks:
 inception:
  driver: bridge
