version: '3'

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      device: /sgoinfre/cbijman/database
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/cbijman/wordpress
      o: bind

services:
  database:
    build: mariadb
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - /goinfre/cbijman/database:/var/lib/mysql
  wordpress:
    depends_on:
      - database
    build: wordpress
    volumes:
      - /goinfre/cbijman/wordpress:/var/www/html
    env_file:
      - .env
  proxy:
    depends_on:
      - wordpress
    build: proxy
    volumes:
      - /goinfre/cbijman/wordpress:/var/www/html
    ports:
      - 8080:8080

