version: '3'

#volumes:
#  database:
#    driver: local
#    driver_opts:
#      type: none
#      device: /sgoinfre/cbijman/database
#      o: bind
#  wordpress:
#    driver: local
#    driver_opts:
#      type: none
#      device: /home/cbijman/wordpress
      #o: bind
services:
  database:
    build: mariadb
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h database --user=$$DB_USER --password=$$DB_PASS
      interval: 2s
      timeout: 10s
      retries: 10
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /Users/cbijman/goinfre/database:/var/lib/mysql
  wordpress:
    depends_on:
      database:
        condition: service_healthy
    build: wordpress
    volumes:
      - /Users/cbijman/goinfre/wordpress:/var/www/html
    env_file:
      - .env
  nginx:
    depends_on:
      - wordpress
    build: nginx
    volumes:
      - /Users/cbijman/goinfre/wordpress:/var/www/html
    ports:
      - 8080:8080

